disabled_rules:
  - identifier_name
  - multiple_closures_with_trailing_closure

excluded: # paths to ignore during linting. overridden by `included`.
  - fastlane

line_length:
  warning: 250
  error: 300
  ignores_comments: true
  ignores_urls: true
